### ISSUE TITLE
Kruskal's algorithm

### ISSUE THREAD

**Issue by anjalii14** [PratikshaChuryaA/Hactoberfest2023#16]
Given a weighted, undirected, and connected graph of V vertices and E edges. The task is to find the sum of weights of the edges of the Minimum Spanning Tree.

**Comment by anjalii14** [comment]
I would like to work on this under hactoberfest

**Comment by anjalii14** [comment]
please assign me this issue

**Comment by Sushobhan-Nayak** [comment]
Can you please assign me this issue, I would like to work on this. Thanks.
